### ISSUE TITLE
glide install fails with "Cannot detect VCS"

### ISSUE THREAD

**Issue by d10r** [kaakaa/matterpoll-emoji#34] opened 2017-07-27 12:25 UTC
```
$ glide install
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Found desired version locally github.com/alecthomas/log4go 3fbce08846379ec7f4f6bc7fce6dd01ce28fae4c!
[INFO]  --> Found desired version locally github.com/gorilla/websocket 3ab3a8b8831546bd18fd182c20687ca853b2bb13!
[INFO]  --> Found desired version locally github.com/mattermost/platform a350f4dc0754e1aeabb64bd712ce05f7c59cfa60!
[INFO]  --> Found desired version locally github.com/nicksnyder/go-i18n 3e70a1a463008cea6726380c908b1a6a8bdf7b24!
[INFO]  --> Found desired version locally github.com/pborman/uuid a97ce2ca70fa5a848076093f05e639a89ca34d06!
[INFO]  --> Found desired version locally github.com/pelletier/go-toml 69d355db5304c0f7f809a2edc054553e7142f016!
[INFO]  --> Fetching gopkg.in/yaml.v2.
[INFO]  --> Fetching golang.org/x/crypto.
[WARN]  Unable to checkout golang.org/x/crypto
[ERROR] Update failed for golang.org/x/crypto: Cannot detect VCS
[WARN]  Unable to checkout gopkg.in/yaml.v2
[ERROR] Update failed for gopkg.in/yaml.v2: Cannot detect VCS
[ERROR] Failed to install: Cannot detect VCS
Cannot detect VCS
```

environment:
```
bot@code:~/matterpoll-emoji$ go version
go version go1.6.2 linux/amd64
bot@code:~/matterpoll-emoji$ glide --version
glide version v0.12.3
```

**Comment by kaakaa** [comment] 2017-07-30 08:20
Thanks for reporting this!

It looks like a problem about glide. 
The following issue may be your help.
[glide get can not detect vcs from package gopkg.in/yaml.v2 · Issue #449 · Masterminds/glide](https://github.com/Masterminds/glide/issues/449#issuecomment-262531171)

Please try to set `git config --global http.sslVerify true` and execute `glide install`?

---

I use `glide version 0.13.0-dev` and have no problem.

**Comment by d10r** [comment] 2017-08-10 22:28
Thanks for the hints.
However neither `git config --global http.sslVerify true` nor updating to glide 0.13.0-dev (aka master branch) nor updating to go 1.8.3 did help.

`go get golang.org/x/crypto` results in
```package golang.org/x/crypto: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: x509: certificate signed by unknown authority)```

I thus tried `git config --global http.sslVerify false` (instead of true), didn't make a difference.

The upstream issue best matching this seems to be https://github.com/Masterminds/glide/issues/893, I also commented there.

**Comment by Hanzei** [comment] 2017-08-23 12:06
#64 removes the dependency on glide. So I'm closing this one.

**Closed by Hanzei** 2017-08-23 12:06 UTC
Labels: bug

**Comment by jingyan** [comment] 2018-04-09 06:47
Set mirror worked for me.

$ glide mirror set https://golang.org/x/crypto https://github.com/golang/crypto --vcs git

**Comment by subbu05** [comment] 2018-06-06 18:19
Resolved the issue. After going though the Glide code understood the root cause. Its not the glide issue. Glide must have flag to ignore server certificates.
Solution: Get Common CA certificates
Ubuntu - https://launchpad.net/ubuntu/xenial/+package/ca-certificates
Similarly search for other OS and install and try.
