### ISSUE TITLE
HTTP response to HTTPS client

### ISSUE THREAD

**Issue by jtschneider** [kaakaa/matterpoll-emoji#103] opened 2018-02-23 11:17 UTC
Hello everyone!

I downloaded the precompiled version 0.1.1

We are running `mattermost server` on the same Host as `matterpoll-emoji` and I added `localhost` as well as `127.0.0.1` to the list of [allowed untrusted internal connections](https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to).

The `config.json` for `matterpoll-emoji` looks like this:
```
{
  "host": "https://localhost:8065",
  "listen": "localhost:8505",
  "token": "r1wk9hqtsjdumg6hqayo7754no",
  "user": {
    "id": "XXX",
    "password": "XXX"
  }
}
```

I also tried ` "host": "localhost:8065"` and ` "host": "{HTTPS-URL}:8065"` which yielded always this error message in the `mattermost server logs`:

`Command with a trigger of 'poll' failed [details: Post https://localhost:8505/poll: http: server gave HTTP response to HTTPS client]`

**Comment by kaakaa** [comment] 2018-02-24 09:55
Hi @ea396! Thank you for reporting.

I tried some settings in my machine.

Do you set `https://loclahost:8505` to `Request URL` in slash command settings?
Sadly matterpoll-emoji doesn't support `https` server settings yet, so you need to set `http://localhost:8505` to `Request URL`.

If you cannot fix errors, please let me know about your slash command settings and Mattermost version.
I'll investigate the cause of your error in more detail.

Thanks.

**Comment by hanzei** [comment] 2018-10-18 15:03
Closing this one since its been without update for a long time.
@jtschneider feel free to reopen it if the problem still occurs.

**Closed by hanzei** 2018-10-18 15:03 UTC
Labels: bug
